@startuml component
person operator

node SemSearchUI [
    Semantic Search UI
]

folder ImageStore as "Image Store"

database SemSearchDB [
    Semantic Search DB
]

rectangle SemanticSearchSvc as "Semantic Search Service" #line:crimson {
    rectangle CaptionVocTreeSvc #crimson [
        Captions Vocabulary Tree Service
        ---
        Provides use cases for
        training, populating,
        replacing and searching
        a vocabulary tree index
        based on caption features.
    ]
    rectangle ImVocTreeSvc #crimson [
        Images Vocabulary Tree Service
        ---
        Provides use cases for
        training, populating,
        replacing and searching
        a vocabulary tree index
        based on image features.
    ]
    rectangle SemSearchSvc #crimson [
        Semantic Search Service
        ---
        Composes vocabulary trees
        to provide search of images
        with and without captions.
        Can fetch image metadata.
    ]
    rectangle TrainController #crimson [
        Train Controller
        ---
        Provides REST API to trigger
        start of training. Manages 
        training and population of 
        vocabulary trees in the
        background.
    ]
    rectangle ImageSearchController as "Image Search Controller" #crimson

    SemSearchSvc --> CaptionVocTreeSvc: Uses
    SemSearchSvc --> ImVocTreeSvc: Uses
    SemSearchSvc --> SemSearchDB: Uses
    CaptionVocTreeSvc --> SemSearchDB: Uses
    ImVocTreeSvc --> SemSearchDB: Uses
    
    TrainController --> CaptionVocTreeSvc: Uses
    TrainController --> ImVocTreeSvc: Uses
    ImageSearchController --> SemSearchSvc: Uses
    operator --> TrainController: Trigger training
    
    SemSearchSvc --> ImageStore: Read images
    ImVocTreeSvc --> ImageStore: Read images

    SemSearchUI --> ImageSearchController: Uses
}
@enduml
